/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/subjects/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar uma matéria
         * @description Cria uma matéria no sistema
         */
        post: operations["createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar um novo espaço
         * @description Cria um novo espaço no sistema
         */
        post: operations["postCreateSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar um recurso
         * @description Cria um recurso no sistema
         */
        post: operations["postCreateResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserves/create/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar uma nova reserva
         * @description Criar uma reserva para um espaço específico na data e horários fornecidos
         */
        post: operations["postCreateReserve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar um novo usuário
         * @description Registra um novo usuário no sistema
         */
        post: operations["postSignUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Realizar logout
         * @description Realiza o logout do usuário
         */
        post: operations["postSignOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Realizar login
         * @description Realiza o login do usuário
         */
        post: operations["postSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar uma matéria
         * @description Edita uma matéria no sistema
         */
        patch: operations["updateSubject"];
        trace?: never;
    };
    "/spaces/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar espaço
         * @description Edita um espaço existente
         */
        patch: operations["patchSpace"];
        trace?: never;
    };
    "/resources/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar um recurso
         * @description Edita um recurso no sistema
         */
        patch: operations["updateResource"];
        trace?: never;
    };
    "/reserves/update/{reserveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar as informações da reserva
         * @description Atualiza as informações da reserva
         */
        patch: operations["updateReserve"];
        trace?: never;
    };
    "/auth/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar as informações do usuario
         * @description Atualiza as informações do usuario no sistema
         */
        patch: operations["patchUpdate"];
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas as matérias
         * @description Lista todas as matérias cadastradas
         */
        get: operations["getSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas as materias cacheadas
         * @description Lista todas as matérias. Destinado ao autocomplete
         */
        get: operations["getCachedSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar por laboratorios
         * @description Retorna uma lista de laboratorios
         */
        get: operations["getSpaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar por recursos
         * @description Retorna uma lista de recursos.
         */
        get: operations["getResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar recursos cache
         * @description Retorna uma lista de recursos. Destinado ao autocomplete.
         */
        get: operations["getResourcesCache"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar reservas por espaço e data
         * @description Retorna uma lista de reservas para um determinado espaço em uma data específica
         */
        get: operations["getReserves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserves/find/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar reservas por espaço e data
         * @description Retorna uma lista de reservas para um determinado espaço em uma data específica
         */
        get: operations["getReservesFromSpace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pesquisar por usuarios
         * @description Filtra e retorna usuarios encontrados. OBS: A rota funciona apenas para admins
         */
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletar uma matéria
         * @description Deleta uma matéria no sistema
         */
        delete: operations["deleteSubject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletar um espaço
         * @description Deleta um espaço do sistema
         */
        delete: operations["deleteSpace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletar um recurso
         * @description Deleta um recurso no sistema
         */
        delete: operations["deleteResource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserves/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletar um conjunto de reservas
         * @description Deleta/cancela um conjunto de reservas do sistema
         */
        delete: operations["deleteReserve"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErroResponseDTO: {
            message: string;
        };
        CreateSpaceRequestDTO: {
            name: string;
            description?: string;
            /** Format: int32 */
            capacity: number;
            resources?: number[];
            subjects?: number[];
        };
        CreateReserveRequestDTO: {
            dates: string[];
            schedules: ("M_AULA_1" | "M_AULA_2" | "M_AULA_3" | "M_AULA_4" | "M_AULA_5" | "V_AULA_1" | "V_AULA_2" | "V_AULA_3" | "V_AULA_4" | "V_AULA_5" | "N_AULA_1" | "N_AULA_2" | "N_AULA_3" | "N_AULA_4")[];
            lock?: boolean;
        };
        RegisterRequestDTO: {
            username: string;
            /** Format: email */
            email: string;
            registration: string;
            password: string;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "USER";
            enabled?: boolean;
        };
        LoginRequestDTO: {
            registration: string;
            password: string;
        };
        LoginResponseDTO: {
            username: string;
            role: string;
            /** Format: int64 */
            tokenExpireIn: number;
        };
        Subject: {
            /** Format: int32 */
            id?: number;
            name?: string;
        };
        PatchSpaceRequestDTO: {
            name?: string;
            /** Format: int32 */
            capacity?: number;
            resources?: number[];
            subjects?: number[];
        };
        Resource: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        UpdateReserveRequestDTO: {
            /** Format: date */
            reservedDate?: string;
            /** @enum {string} */
            schedule?: "M_AULA_1" | "M_AULA_2" | "M_AULA_3" | "M_AULA_4" | "M_AULA_5" | "V_AULA_1" | "V_AULA_2" | "V_AULA_3" | "V_AULA_4" | "V_AULA_5" | "N_AULA_1" | "N_AULA_2" | "N_AULA_3" | "N_AULA_4";
            lock?: boolean;
            userRegistration?: string;
            /** Format: int32 */
            spaceId?: number;
        };
        GrantedAuthority: {
            authority?: string;
        };
        Reserve: {
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date */
            reservedDate?: string;
            /** @enum {string} */
            schedule?: "M_AULA_1" | "M_AULA_2" | "M_AULA_3" | "M_AULA_4" | "M_AULA_5" | "V_AULA_1" | "V_AULA_2" | "V_AULA_3" | "V_AULA_4" | "V_AULA_5" | "N_AULA_1" | "N_AULA_2" | "N_AULA_3" | "N_AULA_4";
            locked?: boolean;
            user?: components["schemas"]["User"];
            space?: components["schemas"]["Space"];
        };
        Space: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            /** Format: int32 */
            capacity?: number;
        };
        User: {
            /** Format: uuid */
            id?: string;
            username?: string;
            email?: string;
            registration?: string;
            password?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "USER";
            enabled?: boolean;
            authorities?: components["schemas"]["GrantedAuthority"][];
            credentialsNonExpired?: boolean;
            accountNonExpired?: boolean;
            accountNonLocked?: boolean;
        };
        UserUpdateRequestDTO: {
            /** Format: uuid */
            uuid?: string;
            registration?: string;
            username?: string;
            email?: string;
            password?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "USER";
            enabled?: boolean;
        };
        UserUpdateResponseDTO: {
            /** Format: uuid */
            id?: string;
            registration: string;
            username: string;
            email: string;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "USER";
            enabled?: boolean;
        };
        SpaceDTO: {
            /** Format: int32 */
            id: number;
            name: string;
            /** Format: int32 */
            capacity: number;
            resources?: number[];
            subjects?: number[];
        };
        SpacesResponseDTO: {
            spaces: components["schemas"]["SpaceDTO"][];
            /** Format: int32 */
            offset: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            total: number;
        };
        ReserveResponseDTO: {
            /** Format: date */
            reservedDate: string;
            reserves: components["schemas"]["Reserve"][];
        };
        UserRequestDTO: {
            registration?: string;
            username?: string;
            /** Format: email */
            email?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "USER";
            /** Format: int32 */
            offset?: number;
            /** Format: int32 */
            limit?: number;
        };
        DeleteSubjectRequestDTO: {
            subjectIds: number[];
        };
        DeleteSpaceDTO: {
            spaceIds: number[];
        };
        DeleteResourceRequestDTO: {
            resourceIds: number[];
        };
        DeleteReserveRequestDTO: {
            reserveIds: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Matéria criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro ao criar matéria */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postCreateSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpaceRequestDTO"];
            };
        };
        responses: {
            /** @description Espaço criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro ao criar espaço */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postCreateResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Recurso criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro ao criar recurso */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postCreateReserve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReserveRequestDTO"];
            };
        };
        responses: {
            /** @description Reserva criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuario nao é administrador */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
            /** @description Espaço não encontrado ou erro na criação da reserva */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postSignUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequestDTO"];
            };
        };
        responses: {
            /** @description Usuário registrado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário já registrado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postSignOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout realizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDTO"];
            };
        };
        responses: {
            /** @description Login realizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDTO"];
                };
            };
            /** @description Matricula ou senha incorretos, conta desabilitada ou conta trancada */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    updateSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Matéria editada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Subject"];
                };
            };
            /** @description Erro ao editar matéria */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    patchSpace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSpaceRequestDTO"];
            };
        };
        responses: {
            /** @description Espaço editado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro ao editar espaço */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Recurso editado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Resource"];
                };
            };
            /** @description Erro ao editar recurso */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    updateReserve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reserveId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReserveRequestDTO"];
            };
        };
        responses: {
            /** @description Reserva(s) deletadas com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Reserve"];
                };
            };
            /** @description Usuario nao é administrador e tentou alterar a reserva de outro usuario */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
            /** @description Reserva(s) nao encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    patchUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequestDTO"];
            };
        };
        responses: {
            /** @description Usuário registrado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserUpdateResponseDTO"];
                };
            };
            /** @description Usuário já registrado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getSubjects: {
        parameters: {
            query?: {
                name?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matérias listadas com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Subject"][];
                };
            };
            /** @description Nenhuma matéria encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getCachedSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matérias listadas com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Subject"][];
                };
            };
        };
    };
    getSpaces: {
        parameters: {
            query?: {
                name?: string;
                capacity?: number;
                resources?: number[];
                subjects?: number[];
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Laboratorios encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SpacesResponseDTO"];
                };
            };
            /** @description Nenhum laboratorio encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getResources: {
        parameters: {
            query?: {
                name?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recursos encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Resource"][];
                };
            };
            /** @description Nenhum recurso encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getResourcesCache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recursos encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Resource"][];
                };
            };
        };
    };
    getReserves: {
        parameters: {
            query: {
                yearMonth: string;
                spaceName?: string;
                username?: string;
                registration?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de reservas encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReserveResponseDTO"][];
                };
            };
            /** @description Nenhuma reserva encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReservesFromSpace: {
        parameters: {
            query: {
                dates: string[];
            };
            header?: never;
            path: {
                spaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de reservas encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReserveResponseDTO"][];
                };
            };
            /** @description Nenhuma reserva encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getUsers: {
        parameters: {
            query?: {
                registration?: string;
                username?: string;
                email?: string;
                role?: "OWNER" | "ADMIN" | "USER";
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retorna lista de usuarios encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserRequestDTO"][];
                };
            };
            /** @description Usuário nao encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteSubjectRequestDTO"];
            };
        };
        responses: {
            /** @description Matéria deletada com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Matéria não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    deleteSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteSpaceDTO"];
            };
        };
        responses: {
            /** @description Espaço deletado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Espaço não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteResourceRequestDTO"];
            };
        };
        responses: {
            /** @description Recurso deletado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    deleteReserve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteReserveRequestDTO"];
            };
        };
        responses: {
            /** @description Reserva(s) deletadas com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reserva(s) nao encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
}
