/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account/@me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Informação da conta
         * @description Retorna informações do usuário autenticado, incluindo ID, matrícula, nome de usuário, e-mail e cargo.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountResponseDTO"];
                        "application/json": components["schemas"]["AccountResponseDTO"];
                        "text/json": components["schemas"]["AccountResponseDTO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar conta
         * @description Edita as informações da conta do usuário autenticado, incluindo nome de usuário.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountEditRequestDTO"];
                    "text/json": components["schemas"]["AccountEditRequestDTO"];
                    "application/*+json": components["schemas"]["AccountEditRequestDTO"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/account/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin: listar usuarios
         * @description Lista todos os usuários cadastrados no sistema.
         */
        get: {
            parameters: {
                query?: {
                    SearchQuery?: string;
                    Role?: components["schemas"]["EAccountRole"];
                    Limit?: number | string;
                    Page?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountResponseDTO"][];
                        "application/json": components["schemas"]["AccountResponseDTO"][];
                        "text/json": components["schemas"]["AccountResponseDTO"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/admin/edit/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Admin: listar usuarios
         * @description Lista todos os usuários cadastrados no sistema.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminAccountEditRequestDTO"];
                    "text/json": components["schemas"]["AdminAccountEditRequestDTO"];
                    "application/*+json": components["schemas"]["AdminAccountEditRequestDTO"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar
         * @description Registra um novo usuário com a role "User" e envia um e-mail de confirmação.
         *     Apenas um Admin/Owner autenticado pode definir outra role através do campo "role".
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignUpRequestDTO"];
                    "text/json": components["schemas"]["SignUpRequestDTO"];
                    "application/*+json": components["schemas"]["SignUpRequestDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IdentityError"][];
                        "application/json": components["schemas"]["IdentityError"][];
                        "text/json": components["schemas"]["IdentityError"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Confirmar e-mail
         * @description Rota aberta pelo link enviado por e-mail após o cadastro.
         */
        get: operations["ConfirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reenviar confirmação de e-mail
         * @description Responde sempre 202, exista a conta ou não, para não revelar quais e-mails estão cadastrados.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailRequestDTO"];
                    "text/json": components["schemas"]["EmailRequestDTO"];
                    "application/*+json": components["schemas"]["EmailRequestDTO"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Entrar
         * @description Autentica por matrícula e senha e grava o cookie de sessão.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignInRequestDTO"];
                    "text/json": components["schemas"]["SignInRequestDTO"];
                    "application/*+json": components["schemas"]["SignInRequestDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sair
         * @description Remove o cookie de sessão.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar redefinição de senha
         * @description Envia um e-mail com o link para o front-end. Responde sempre 202, exista a conta ou não.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailRequestDTO"];
                    "text/json": components["schemas"]["EmailRequestDTO"];
                    "application/*+json": components["schemas"]["EmailRequestDTO"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redefinir senha
         * @description Troca a senha usando o token recebido por e-mail.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequestDTO"];
                    "text/json": components["schemas"]["ResetPasswordRequestDTO"];
                    "application/*+json": components["schemas"]["ResetPasswordRequestDTO"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IdentityError"][];
                        "application/json": components["schemas"]["IdentityError"][];
                        "text/json": components["schemas"]["IdentityError"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todos os recursos
         * @description Lista todas os recursos cadastradas
         */
        get: {
            parameters: {
                query?: {
                    SearchQuery?: string;
                    CanReserve?: boolean;
                    Enabled?: boolean;
                    Limit?: number | string;
                    Offset?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceResponseDTO"][];
                        "application/json": components["schemas"]["ResourceResponseDTO"][];
                        "text/json": components["schemas"]["ResourceResponseDTO"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource/admin/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar recurso
         * @description Cria um novo recurso. Apenas usuários com permissões adequadas podem criar recursos.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResourceCreateRequestDTO"];
                    "text/json": components["schemas"]["ResourceCreateRequestDTO"];
                    "application/*+json": components["schemas"]["ResourceCreateRequestDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource/admin/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar recurso
         * @description Edita um recurso existente. Apenas usuários com permissões adequadas podem editar recursos.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResourceEditRequestDTO"];
                    "text/json": components["schemas"]["ResourceEditRequestDTO"];
                    "application/*+json": components["schemas"]["ResourceEditRequestDTO"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/resource-reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar reservas
         * @description Lista todas as reservas de recursos cadastradas de acordo com os filtros fornecidos
         */
        get: {
            parameters: {
                query?: {
                    SearchQuery?: string;
                    SpaceIds?: (number | string)[];
                    Limit?: number | string;
                    Offset?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceReserveResponseDTO"][];
                        "application/json": components["schemas"]["ResourceReserveResponseDTO"][];
                        "text/json": components["schemas"]["ResourceReserveResponseDTO"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-reserve/create/{spaceReserveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar reserva
         * @description Cria uma nova reserva para o recurso especificado para um espaço especifico
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceReserveId: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResourceReserveCreateRequestDTO"];
                    "text/json": components["schemas"]["ResourceReserveCreateRequestDTO"];
                    "application/*+json": components["schemas"]["ResourceReserveCreateRequestDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-reserve/edit/{resourceReserveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar reserva
         * @description Edita uma reserva existente para o recurso especificado para um espaço especifico
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    resourceReserveId: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResourceReserveEditRequestDTO"];
                    "text/json": components["schemas"]["ResourceReserveEditRequestDTO"];
                    "application/*+json": components["schemas"]["ResourceReserveEditRequestDTO"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/resource-reserve/cancel/{resourceReserveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Calcelar reserva
         * @description Cancela uma reserva existente para o recurso especificado para um espaço especifico
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    resourceReserveId: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todos os espaços
         * @description Lista todos os espaços cadastrados
         */
        get: {
            parameters: {
                query?: {
                    SearchQuery?: string;
                    Capacity?: number | string;
                    Resources?: (number | string)[];
                    Subjects?: (number | string)[];
                    StartAt?: string;
                    EndAt?: string;
                    Schedules?: (number | string)[];
                    Locked?: boolean;
                    Limit?: number | string;
                    Offset?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SpaceResponseDTO"][];
                        "application/json": components["schemas"]["SpaceResponseDTO"][];
                        "text/json": components["schemas"]["SpaceResponseDTO"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space/admin/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar espaço
         * @description Cria um novo espaço com base nos parâmetros fornecidos. Apenas usuários com permissões adequadas podem criar espaços.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SpaceCreateRequestDTO"];
                    "text/json": components["schemas"]["SpaceCreateRequestDTO"];
                    "application/*+json": components["schemas"]["SpaceCreateRequestDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space/admin/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar espaço
         * @description Edita os dados de um espaço existente. Apenas usuários com permissões adequadas podem editar espaços.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SpaceEditRequestDTO"];
                    "text/json": components["schemas"]["SpaceEditRequestDTO"];
                    "application/*+json": components["schemas"]["SpaceEditRequestDTO"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/space-reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar reservas
         * @description Lista todas as reservas de espaços cadastradas de acordo com os filtros fornecidos
         */
        get: {
            parameters: {
                query?: {
                    StartAt?: string;
                    EndAt?: string;
                    SpaceIds?: (number | string)[];
                    Status?: components["schemas"]["EReserveStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SpaceResponseDTO"][];
                        "application/json": components["schemas"]["SpaceResponseDTO"][];
                        "text/json": components["schemas"]["SpaceResponseDTO"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space-reserve/existing-schedules/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pegar horarios
         * @description Retorna uma lista de horarios ja reservados para um espaco especifico de acordo com data range fornecido
         */
        get: {
            parameters: {
                query?: {
                    StartAt?: string;
                    EndAt?: string;
                };
                header?: never;
                path: {
                    spaceId: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ScheduleResponseDTO"][];
                        "application/json": components["schemas"]["ScheduleResponseDTO"][];
                        "text/json": components["schemas"]["ScheduleResponseDTO"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space-reserve/create/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar reserva
         * @description Cria uma nova reserva para o espaço especificado, com base nas datas fornecidas e no usuário autenticado
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SpaceReserveCreateRequestDTO"];
                    "text/json": components["schemas"]["SpaceReserveCreateRequestDTO"];
                    "application/*+json": components["schemas"]["SpaceReserveCreateRequestDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space-reserve/edit/{reserveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar reserva
         * @description Edita a data e horário de uma reserva de espaço existente.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reserveId: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SpaceReserveEditRequestDTO"];
                    "text/json": components["schemas"]["SpaceReserveEditRequestDTO"];
                    "application/*+json": components["schemas"]["SpaceReserveEditRequestDTO"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/space-reserve/cancel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancelar reserva
         * @description Cancela uma reserva de espaço existente.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space-reserve/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin: listar reservas
         * @description Lista todos os espaços cadastrados
         */
        get: {
            parameters: {
                query?: {
                    StartAt?: string;
                    EndAt?: string;
                    SpaceIds?: (number | string)[];
                    ScheduleIds?: (number | string)[];
                    Status?: components["schemas"]["EReserveStatus"];
                    AccountIds?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SpaceResponseDTO"][];
                        "application/json": components["schemas"]["SpaceResponseDTO"][];
                        "text/json": components["schemas"]["SpaceResponseDTO"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/space-reserve/admin/edit/{reserveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Admin: editar reserva
         * @description Edita status de uma reserva de espaço existente.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reserveId: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminSpaceReserveEditRequestDTO"];
                    "text/json": components["schemas"]["AdminSpaceReserveEditRequestDTO"];
                    "application/*+json": components["schemas"]["AdminSpaceReserveEditRequestDTO"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/subject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas as matérias
         * @description Lista todas as matérias cadastradas
         */
        get: {
            parameters: {
                query?: {
                    Name?: string;
                    IsActive?: boolean;
                    Limit?: number | string;
                    Offset?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubjectResponseDTO"][];
                        "application/json": components["schemas"]["SubjectResponseDTO"][];
                        "text/json": components["schemas"]["SubjectResponseDTO"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject/admin/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar matéria
         * @description Cria uma nova matéria. Apenas usuários com permissões adequadas podem criar matérias.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubjectCreateRequestDTO"];
                    "text/json": components["schemas"]["SubjectCreateRequestDTO"];
                    "application/*+json": components["schemas"]["SubjectCreateRequestDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subject/admin/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar matéria
         * @description Edita os dados de uma matéria. Apenas usuários com permissões adequadas podem editar matérias.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubjectEditRequestDTO"];
                    "text/json": components["schemas"]["SubjectEditRequestDTO"];
                    "application/*+json": components["schemas"]["SubjectEditRequestDTO"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErroResponseDTO"];
                        "application/json": components["schemas"]["ErroResponseDTO"];
                        "text/json": components["schemas"]["ErroResponseDTO"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountEditRequestDTO: {
            username: string;
        };
        AccountResponseDTO: {
            id: string;
            registration: string;
            username: string;
            email: string;
            role: components["schemas"]["EAccountRole"];
        };
        AdminAccountEditRequestDTO: {
            registration: null | string;
            username: null | string;
            role: null | components["schemas"]["EAccountRole"];
            lockAccount: null | boolean;
        };
        AdminSpaceReserveEditRequestDTO: {
            status: components["schemas"]["EReserveStatus"];
        };
        EAccountRole: number;
        EmailRequestDTO: {
            email: string;
        };
        EReserveStatus: number;
        ErroResponseDTO: {
            message: string;
            /** Format: int32 */
            statusCode: number | string;
            /** @default false */
            logout: boolean;
        };
        EShift: number;
        IdentityError: {
            code?: string;
            description?: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ResetPasswordRequestDTO: {
            email: string;
            token: string;
            newPassword: string;
        };
        ResourceCreateRequestDTO: {
            name: string;
            description: string;
            /** @default false */
            canReserve: boolean;
            /** @default true */
            enabled: boolean;
        };
        ResourceEditRequestDTO: {
            /** Format: int64 */
            id: number | string;
            name: null | string;
            description: null | string;
            canReserve: null | boolean;
            enabled: null | boolean;
        };
        ResourceReserveCreateRequestDTO: {
            /** Format: int64 */
            resourceId: number | string;
            purpose: string;
        };
        ResourceReserveEditRequestDTO: {
            /** Format: int64 */
            spaceReserveId: number | string;
            purpose: null | string;
        };
        ResourceReserveResponseDTO: {
            /** Format: int64 */
            id: number | string;
            name: string;
            description: string;
            spaceReserve: components["schemas"]["SpaceReserveResponseDTO"];
        };
        ResourceResponseDTO: {
            /** Format: int64 */
            id: number | string;
            name: string;
            description: string;
            canReserve: boolean;
            enabled: boolean;
        };
        ScheduleResponseDTO: {
            /** Format: int64 */
            id: number | string;
            /** Format: time */
            startAt: string;
            /** Format: time */
            endAt: string;
            shift: components["schemas"]["EShift"];
        };
        SignInRequestDTO: {
            registration: string;
            password: string;
            /** @default false */
            rememberMe: boolean;
        };
        SignUpRequestDTO: {
            username: string;
            registration: string;
            email: string;
            password: string;
        };
        SpaceCreateRequestDTO: {
            name: string;
            description: string;
            /** Format: int32 */
            capacity: number | string;
            locked: boolean;
            subjects: (number | string)[];
            resources: (number | string)[];
        };
        SpaceEditRequestDTO: {
            /** Format: int64 */
            id: number | string;
            name: null | string;
            description: null | string;
            /** Format: int32 */
            capacity: null | number | string;
            locked: null | boolean;
            subjects: null | (number | string)[];
            resources: null | (number | string)[];
        };
        SpaceHashDataDTO: {
            /** Format: int64 */
            id: number | string;
            name: string;
        };
        SpaceReserveCreateRequestDTO: {
            /** Format: date */
            startAt: string;
            /** Format: date */
            endAt: string;
            scheduleIds: (number | string)[];
            purpose: string;
        };
        SpaceReserveEditRequestDTO: {
            /** Format: date */
            startAt: null | string;
            /** Format: date */
            endAt: null | string;
            scheduleIds: null | (number | string)[];
        };
        SpaceReserveResponseDTO: {
            /** Format: int64 */
            id: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo: string;
            purpose: string;
            status: components["schemas"]["EReserveStatus"];
            space: components["schemas"]["SpaceResponseDTO"];
            schedules: components["schemas"]["ScheduleResponseDTO"][];
        };
        SpaceResponseDTO: {
            /** Format: int64 */
            id: number | string;
            name: string;
            /** Format: int32 */
            capacity: number | string;
            description: string;
            locked: boolean;
            subjects: components["schemas"]["SpaceHashDataDTO"][];
            resources: components["schemas"]["SpaceHashDataDTO"][];
        };
        SubjectCreateRequestDTO: {
            name: string;
            /** @default false */
            enabled: boolean;
        };
        SubjectEditRequestDTO: {
            /** Format: int64 */
            id: number | string;
            name: null | string;
            enabled: null | boolean;
        };
        SubjectResponseDTO: {
            /** Format: int64 */
            id: number | string;
            name: string;
            enabled: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ConfirmEmail: {
        parameters: {
            query?: {
                UserId?: string;
                Token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["IdentityError"][];
                    "application/json": components["schemas"]["IdentityError"][];
                    "text/json": components["schemas"]["IdentityError"][];
                };
            };
        };
    };
}
