/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/subjects/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar uma matéria
         * @description Cria uma matéria no sistema
         */
        post: operations["createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar um novo espaço
         * @description Cria um novo espaço no sistema
         */
        post: operations["postCreateSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar um recurso
         * @description Cria um recurso no sistema
         */
        post: operations["postCreateResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserve/create/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria uma nova reserva
         * @description Cria uma nova reserva para o espaço especificado, com base nas datas fornecidas e no usuário autenticado
         */
        post: operations["createReserve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar um novo usuário
         * @description Registra um novo usuário no sistema
         */
        post: operations["postSignUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Realizar logout
         * @description Realiza o logout do usuário
         */
        post: operations["postSignOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Realizar login
         * @description Realiza o login do usuário
         */
        post: operations["postSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-update-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar email para redefinição de email
         * @description Envia um email para o usuário redefinir o email da conta
         */
        post: operations["postRequestUpdateEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atualiza os cookies do token de acesso e informações da sessão
         * @description Atualiza os cookies do token de acesso e informações da sessão do usuário
         */
        post: operations["getRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar email para redefinição de senha
         * @description Envia um email para o usuário redefinir sua senha
         */
        post: operations["postForgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/manage/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar as informações do usuario
         * @description Atualiza as informações do usuario no sistema
         */
        patch: operations["patchUpdate"];
        trace?: never;
    };
    "/subjects/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar uma matéria
         * @description Edita uma matéria no sistema
         */
        patch: operations["updateSubject"];
        trace?: never;
    };
    "/spaces/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar espaço
         * @description Edita um espaço existente
         */
        patch: operations["patchSpace"];
        trace?: never;
    };
    "/resources/update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar um recurso
         * @description Edita um recurso no sistema
         */
        patch: operations["updateResource"];
        trace?: never;
    };
    "/reserve/edit-date/{reserveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edita a data da reserva
         * @description Edita a data da reserva
         */
        patch: operations["editReserve"];
        trace?: never;
    };
    "/auth/update-password/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar senha do usuário
         * @description Substitui a senha antiga pela nova utilizando o token de validação recebido por e-mail
         */
        patch: operations["postUpdatePassword"];
        trace?: never;
    };
    "/auth/update-email/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar email do usuário
         * @description Substitui o email antigo pelo novo utilizando o token de validação recebido por e-mail
         */
        patch: operations["postUpdatePassword_1"];
        trace?: never;
    };
    "/user/manage/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pesquisar por usuarios
         * @description Filtra e retorna usuarios encontrados. OBS: A rota funciona apenas para admins
         */
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas as matérias
         * @description Lista todas as matérias cadastradas
         */
        get: operations["getSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas as materias cacheadas
         * @description Lista todas as matérias. Destinado ao autocomplete
         */
        get: operations["getCachedSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar por laboratorios
         * @description Retorna uma lista de laboratorios
         */
        get: operations["getSpaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar por recursos
         * @description Retorna uma lista de recursos.
         */
        get: operations["getResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar recursos cache
         * @description Retorna uma lista de recursos. Destinado ao autocomplete.
         */
        get: operations["getResourcesCache"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar historico de reservas do mes
         * @description Retorna uma lista de reservas(confirmada, concluida e cancelada) de um mes especifico
         */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserve/existing-schedules/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cria uma nova reserva
         * @description Cria uma nova reserva para o espaço especificado, com base nas datas fornecidas e no usuário autenticado
         */
        get: operations["getExistingSchedules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserve/date-info/{reserveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtem a data da reserva pelo id
         * @description Retorna a data da reserva
         */
        get: operations["getDateInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletar uma matéria
         * @description Deleta uma matéria no sistema
         */
        delete: operations["deleteSubject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletar um espaço
         * @description Deleta um espaço do sistema
         */
        delete: operations["deleteSpace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletar um recurso
         * @description Deleta um recurso no sistema
         */
        delete: operations["deleteResource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserve/history/cancel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancela uma reserva do historico do usuario pelo id
         * @description Marca a reserva como cancelada
         */
        delete: operations["getHistoryByYearMonth"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErroResponseDTO: {
            message: string;
            logout?: boolean;
        };
        CreateSpaceRequestDTO: {
            name: string;
            description?: string;
            /** Format: int32 */
            capacity: number;
            resources?: number[];
            subjects?: number[];
        };
        CreateReserveRequestDTO: {
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo: string;
            schedules: ("M_AULA_1" | "M_AULA_2" | "M_AULA_3" | "M_AULA_4" | "M_AULA_5" | "V_AULA_1" | "V_AULA_2" | "V_AULA_3" | "V_AULA_4" | "V_AULA_5" | "N_AULA_1" | "N_AULA_2" | "N_AULA_3" | "N_AULA_4")[];
            purpose: string;
            lock?: boolean;
        };
        SignUpRequestDTO: {
            username: string;
            /** Format: email */
            email: string;
            registration: string;
            password: string;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "USER";
            enabled?: boolean;
        };
        SignInRequestDTO: {
            registration: string;
            password: string;
        };
        ForgotPasswordRequestDTO: {
            /** Format: email */
            email: string;
        };
        ManageUserUpdateRequestDTO: {
            registration?: string;
            username?: string;
            email?: string;
            password?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "USER";
            enabled?: boolean;
        };
        Subject: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        PatchSpaceRequestDTO: {
            name?: string;
            /** Format: int32 */
            capacity?: number;
            resources?: number[];
            subjects?: number[];
        };
        GrantedAuthority: {
            authority?: string;
        };
        Reserve: {
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date */
            reservedDateFrom?: string;
            /** Format: date */
            reservedDateTo?: string;
            /** @enum {string} */
            status?: "CONFIRMED" | "PENDING" | "LOCKED" | "CANCELED";
            purpose?: string;
            user?: components["schemas"]["User"];
            space?: unknown;
            schedules?: components["schemas"]["ReserveSchedule"][];
        };
        ReserveSchedule: {
            /** Format: int32 */
            id?: number;
            /** @enum {string} */
            schedule?: "M_AULA_1" | "M_AULA_2" | "M_AULA_3" | "M_AULA_4" | "M_AULA_5" | "V_AULA_1" | "V_AULA_2" | "V_AULA_3" | "V_AULA_4" | "V_AULA_5" | "N_AULA_1" | "N_AULA_2" | "N_AULA_3" | "N_AULA_4";
            reserve?: components["schemas"]["Reserve"];
        };
        Resource: {
            /** Format: int32 */
            id: number;
            name: string;
            spaces?: components["schemas"]["SpaceResource"][];
        };
        Space: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            /** Format: int32 */
            capacity?: number;
            locked?: boolean;
            resources?: components["schemas"]["SpaceResource"][];
            subjects?: components["schemas"]["SpaceSubject"][];
            reserves?: components["schemas"]["Reserve"][];
        };
        SpaceResource: {
            /** Format: int32 */
            id?: number;
            space?: components["schemas"]["Space"];
            resource?: components["schemas"]["Resource"];
        };
        SpaceSubject: {
            /** Format: int32 */
            id?: number;
            space?: components["schemas"]["Space"];
            subject?: components["schemas"]["Subject"];
        };
        User: {
            /** Format: uuid */
            id?: string;
            username?: string;
            email?: string;
            registration?: string;
            password?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "USER";
            enabled?: boolean;
            reserves?: components["schemas"]["Reserve"][];
            nickname?: string;
            authorities?: components["schemas"]["GrantedAuthority"][];
            accountNonExpired?: boolean;
            credentialsNonExpired?: boolean;
            accountNonLocked?: boolean;
        };
        ReserveDateDTO: {
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo: string;
        };
        UpdatePasswordRequestDTO: {
            password: string;
        };
        EmailUpdateRequestDTO: {
            /** Format: email */
            email?: string;
        };
        ManageUserRequestDTO: {
            registration?: string;
            username?: string;
            /** Format: email */
            email?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "USER";
            /** Format: int32 */
            offset?: number;
            /** Format: int32 */
            limit?: number;
        };
        ResourceDTO: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        SpaceDTO: {
            /** Format: int32 */
            id: number;
            name: string;
            /** Format: int32 */
            capacity: number;
            description?: string;
            resources?: components["schemas"]["ResourceDTO"][];
            subjects?: components["schemas"]["SubjectDTO"][];
            locked?: boolean;
        };
        SpacesResponseDTO: {
            spaces: components["schemas"]["SpaceDTO"][];
            /** Format: int32 */
            offset: number;
            /** Format: int32 */
            limit: number;
        };
        SubjectDTO: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        ReserveHistoryDTO: {
            next?: components["schemas"]["ReserveScheduleDTO"][];
            concluded?: components["schemas"]["ReserveScheduleDTO"][];
            canceled?: components["schemas"]["ReserveScheduleDTO"][];
        };
        ReserveScheduleDTO: {
            reserve: components["schemas"]["ReserveSummaryDTO"];
            schedules: ("M_AULA_1" | "M_AULA_2" | "M_AULA_3" | "M_AULA_4" | "M_AULA_5" | "V_AULA_1" | "V_AULA_2" | "V_AULA_3" | "V_AULA_4" | "V_AULA_5" | "N_AULA_1" | "N_AULA_2" | "N_AULA_3" | "N_AULA_4")[];
        };
        ReserveSummaryDTO: {
            /** Format: int32 */
            id: number;
            spaceName: string;
            /** Format: int32 */
            capacity: number;
            /** Format: date */
            reservedDateFrom: string;
            /** Format: date */
            reservedDateTo: string;
            /** @enum {string} */
            status: "CONFIRMED" | "PENDING" | "LOCKED" | "CANCELED";
            purpose: string;
        };
        DeleteSubjectRequestDTO: {
            subjectIds: number[];
        };
        DeleteSpaceDTO: {
            spaceIds: number[];
        };
        DeleteResourceRequestDTO: {
            resourceIds: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Matéria criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro ao criar matéria */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postCreateSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpaceRequestDTO"];
            };
        };
        responses: {
            /** @description Espaço criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro ao criar espaço */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postCreateResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Recurso criado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro ao criar recurso */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    createReserve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReserveRequestDTO"];
            };
        };
        responses: {
            /** @description Reserva criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados da reserva inválidos ou conflitantes */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
            /** @description Autenticação do usuario ou espaço não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postSignUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequestDTO"];
            };
        };
        responses: {
            /** @description Usuário registrado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário já registrado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postSignOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout realizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequestDTO"];
            };
        };
        responses: {
            /** @description Login realizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Matricula ou senha incorretos, conta desabilitada ou conta trancada */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postRequestUpdateEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequestDTO"];
            };
        };
        responses: {
            /** @description Email de redefinição enviado com sucesso */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login realizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Matricula ou senha incorretos, conta desabilitada ou conta trancada */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postForgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequestDTO"];
            };
        };
        responses: {
            /** @description Email de redefinição de senha enviado com sucesso */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    patchUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ManageUserUpdateRequestDTO"];
            };
        };
        responses: {
            /** @description Usuário atualizado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não encontrado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    updateSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Matéria editada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Subject"];
                };
            };
            /** @description Erro ao editar matéria */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    patchSpace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSpaceRequestDTO"];
            };
        };
        responses: {
            /** @description Espaço editado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro ao editar espaço */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Recurso editado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Resource"];
                };
            };
            /** @description Erro ao editar recurso */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    editReserve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reserveId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveDateDTO"];
            };
        };
        responses: {
            /** @description Reserva editada com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reserva conflita com horarios ja reservados */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
            /** @description Nao pode editar reserva de outro usuario */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
            /** @description Reserva nao encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postUpdatePassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordRequestDTO"];
            };
        };
        responses: {
            /** @description Senha atualizada com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token inválido ou expirado ou senha inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    postUpdatePassword_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailUpdateRequestDTO"];
            };
        };
        responses: {
            /** @description Email atualizado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token inválido ou expirado ou email inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getUsers: {
        parameters: {
            query?: {
                registration?: string;
                username?: string;
                email?: string;
                role?: "OWNER" | "ADMIN" | "USER";
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retorna lista de usuarios encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ManageUserRequestDTO"][];
                };
            };
            /** @description Usuário nao encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getSubjects: {
        parameters: {
            query?: {
                name?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matérias listadas com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Subject"][];
                };
            };
            /** @description Nenhuma matéria encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getCachedSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matérias listadas com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Subject"][];
                };
            };
        };
    };
    getSpaces: {
        parameters: {
            query?: {
                name?: string;
                capacity?: number;
                resources?: number[];
                subjects?: number[];
                offset?: number;
                limit?: number;
                locked?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Laboratorios encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SpacesResponseDTO"];
                };
            };
            /** @description Nenhum laboratorio encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getResources: {
        parameters: {
            query?: {
                name?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recursos encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Resource"][];
                };
            };
            /** @description Nenhum recurso encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getResourcesCache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recursos encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Resource"][];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query: {
                yearMonth: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de reservas encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReserveHistoryDTO"];
                };
            };
            /** @description Nenhuma reserva encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getExistingSchedules: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
            };
            header?: never;
            path: {
                spaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserva criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": ("M_AULA_1" | "M_AULA_2" | "M_AULA_3" | "M_AULA_4" | "M_AULA_5" | "V_AULA_1" | "V_AULA_2" | "V_AULA_3" | "V_AULA_4" | "V_AULA_5" | "N_AULA_1" | "N_AULA_2" | "N_AULA_3" | "N_AULA_4")[];
                };
            };
            /** @description Dados da reserva inválidos ou conflitantes */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
            /** @description Autenticação do usuario ou espaço não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getDateInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reserveId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Data da reserve */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReserveDateDTO"];
                };
            };
            /** @description Reserva nao encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    deleteSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteSubjectRequestDTO"];
            };
        };
        responses: {
            /** @description Matéria deletada com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Matéria não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    deleteSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteSpaceDTO"];
            };
        };
        responses: {
            /** @description Espaço deletado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Espaço não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteResourceRequestDTO"];
            };
        };
        responses: {
            /** @description Recurso deletado com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
    getHistoryByYearMonth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserva cancelada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Provavelmente esta alterando reserva de outro usuario */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
            /** @description Usuario ou reserva encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErroResponseDTO"];
                };
            };
        };
    };
}
