/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reserves/create/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria uma nova reserva
         * @description Cria uma reserva para um espaço específico na data e horários fornecidos
         */
        post: operations["postCreateReserve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca por laboratorios
         * @description Retorna uma lista de laboratorios
         */
        get: operations["getSpaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reserves/find/{spaceId}/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca reservas por espaço e data
         * @description Retorna uma lista de reservas para um determinado espaço em uma data específica
         */
        get: operations["getReserve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReserveBody: {
            /** Format: date */
            date?: string;
            schedules?: ("M_AULA_1" | "M_AULA_2" | "M_AULA_3" | "M_AULA_4" | "M_AULA_5" | "V_AULA_1" | "V_AULA_2" | "V_AULA_3" | "V_AULA_4" | "V_AULA_5" | "N_AULA_1" | "N_AULA_2" | "N_AULA_3" | "N_AULA_4")[];
        };
        SpaceResources: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            resource?: "TELAO" | "COMPUTADORES" | "TUBOS_DE_ENSAIO";
            space?: components["schemas"]["Spaces"];
        };
        Spaces: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int32 */
            capacity?: number;
            resources?: ("TELAO" | "COMPUTADORES" | "TUBOS_DE_ENSAIO")[];
        };
        SpacesResponse: {
            space?: components["schemas"]["Spaces"];
            resources?: components["schemas"]["SpaceResources"][];
        };
        Reserves: {
            /** Format: int64 */
            id?: number;
            /** Format: date */
            reservedDate?: string;
            /** @enum {string} */
            schedule?: "M_AULA_1" | "M_AULA_2" | "M_AULA_3" | "M_AULA_4" | "M_AULA_5" | "V_AULA_1" | "V_AULA_2" | "V_AULA_3" | "V_AULA_4" | "V_AULA_5" | "N_AULA_1" | "N_AULA_2" | "N_AULA_3" | "N_AULA_4";
            space?: components["schemas"]["Spaces"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postCreateReserve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveBody"];
            };
        };
        responses: {
            /** @description Reserva criada com sucesso */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Espaço não encontrado ou erro na criação da reserva */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSpaces: {
        parameters: {
            query?: {
                name?: string;
                capacity?: number;
                resources?: ("TELAO" | "COMPUTADORES" | "TUBOS_DE_ENSAIO")[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Laboratorios encontrados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SpacesResponse"][];
                };
            };
            /** @description Nenhum laboratorio encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SpacesResponse"][];
                };
            };
        };
    };
    getReserve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: number;
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de reservas encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Reserves"][];
                };
            };
            /** @description Nenhuma reserva encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Reserves"][];
                };
            };
        };
    };
}
