/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateAdminRouteRouteImport } from './routes/_private/admin/route'
import { Route as PrivateHistoryRouteImport } from './routes/_private/history'
import { Route as PrivateHomeRouteImport } from './routes/_private/home'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicForgetPasswordRouteImport } from './routes/_public/forget-password'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PrivateAdminManageReservesRouteImport } from './routes/_private/admin/manage-reserves'
import { Route as PrivateAdminManageSpacesRouteImport } from './routes/_private/admin/manage-spaces'
import { Route as PrivateAdminManageUsersRouteImport } from './routes/_private/admin/manage-users'
import { Route as PrivateAdminReportRouteImport } from './routes/_private/admin/report'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAdminRouteRoute = PrivateAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateHistoryRoute = PrivateHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateHomeRoute = PrivateHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicForgetPasswordRoute = PublicForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateAdminManageReservesRoute =
  PrivateAdminManageReservesRouteImport.update({
    id: '/manage-reserves',
    path: '/manage-reserves',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminManageSpacesRoute =
  PrivateAdminManageSpacesRouteImport.update({
    id: '/manage-spaces',
    path: '/manage-spaces',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminManageUsersRoute = PrivateAdminManageUsersRouteImport.update({
  id: '/manage-users',
  path: '/manage-users',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminReportRoute = PrivateAdminReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof PrivateAdminRouteRouteWithChildren
  '/history': typeof PrivateHistoryRoute
  '/home': typeof PrivateHomeRoute
  '/forget-password': typeof PublicForgetPasswordRoute
  '/sign-up': typeof PublicSignUpRoute
  '/admin/manage-reserves': typeof PrivateAdminManageReservesRoute
  '/admin/manage-spaces': typeof PrivateAdminManageSpacesRoute
  '/admin/manage-users': typeof PrivateAdminManageUsersRoute
  '/admin/report': typeof PrivateAdminReportRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof PrivateAdminRouteRouteWithChildren
  '/history': typeof PrivateHistoryRoute
  '/home': typeof PrivateHomeRoute
  '/forget-password': typeof PublicForgetPasswordRoute
  '/sign-up': typeof PublicSignUpRoute
  '/admin/manage-reserves': typeof PrivateAdminManageReservesRoute
  '/admin/manage-spaces': typeof PrivateAdminManageSpacesRoute
  '/admin/manage-users': typeof PrivateAdminManageUsersRoute
  '/admin/report': typeof PrivateAdminReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/admin': typeof PrivateAdminRouteRouteWithChildren
  '/_private/history': typeof PrivateHistoryRoute
  '/_private/home': typeof PrivateHomeRoute
  '/_public/forget-password': typeof PublicForgetPasswordRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/admin/manage-reserves': typeof PrivateAdminManageReservesRoute
  '/_private/admin/manage-spaces': typeof PrivateAdminManageSpacesRoute
  '/_private/admin/manage-users': typeof PrivateAdminManageUsersRoute
  '/_private/admin/report': typeof PrivateAdminReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/history'
    | '/home'
    | '/forget-password'
    | '/sign-up'
    | '/admin/manage-reserves'
    | '/admin/manage-spaces'
    | '/admin/manage-users'
    | '/admin/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/history'
    | '/home'
    | '/forget-password'
    | '/sign-up'
    | '/admin/manage-reserves'
    | '/admin/manage-spaces'
    | '/admin/manage-users'
    | '/admin/report'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/admin'
    | '/_private/history'
    | '/_private/home'
    | '/_public/forget-password'
    | '/_public/sign-up'
    | '/_public/'
    | '/_private/admin/manage-reserves'
    | '/_private/admin/manage-spaces'
    | '/_private/admin/manage-users'
    | '/_private/admin/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/admin': {
      id: '/_private/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/history': {
      id: '/_private/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof PrivateHistoryRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/home': {
      id: '/_private/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PrivateHomeRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/forget-password': {
      id: '/_public/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof PublicForgetPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/admin/manage-reserves': {
      id: '/_private/admin/manage-reserves'
      path: '/manage-reserves'
      fullPath: '/admin/manage-reserves'
      preLoaderRoute: typeof PrivateAdminManageReservesRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/manage-spaces': {
      id: '/_private/admin/manage-spaces'
      path: '/manage-spaces'
      fullPath: '/admin/manage-spaces'
      preLoaderRoute: typeof PrivateAdminManageSpacesRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/manage-users': {
      id: '/_private/admin/manage-users'
      path: '/manage-users'
      fullPath: '/admin/manage-users'
      preLoaderRoute: typeof PrivateAdminManageUsersRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/report': {
      id: '/_private/admin/report'
      path: '/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof PrivateAdminReportRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
  }
}

interface PrivateAdminRouteRouteChildren {
  PrivateAdminManageReservesRoute: typeof PrivateAdminManageReservesRoute
  PrivateAdminManageSpacesRoute: typeof PrivateAdminManageSpacesRoute
  PrivateAdminManageUsersRoute: typeof PrivateAdminManageUsersRoute
  PrivateAdminReportRoute: typeof PrivateAdminReportRoute
}

const PrivateAdminRouteRouteChildren: PrivateAdminRouteRouteChildren = {
  PrivateAdminManageReservesRoute: PrivateAdminManageReservesRoute,
  PrivateAdminManageSpacesRoute: PrivateAdminManageSpacesRoute,
  PrivateAdminManageUsersRoute: PrivateAdminManageUsersRoute,
  PrivateAdminReportRoute: PrivateAdminReportRoute,
}

const PrivateAdminRouteRouteWithChildren =
  PrivateAdminRouteRoute._addFileChildren(PrivateAdminRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateAdminRouteRoute: typeof PrivateAdminRouteRouteWithChildren
  PrivateHistoryRoute: typeof PrivateHistoryRoute
  PrivateHomeRoute: typeof PrivateHomeRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAdminRouteRoute: PrivateAdminRouteRouteWithChildren,
  PrivateHistoryRoute: PrivateHistoryRoute,
  PrivateHomeRoute: PrivateHomeRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicForgetPasswordRoute: typeof PublicForgetPasswordRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicForgetPasswordRoute: PublicForgetPasswordRoute,
  PublicSignUpRoute: PublicSignUpRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
