/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateHistoryRouteImport } from './routes/_private/history'
import { Route as PrivateHomeRouteImport } from './routes/_private/home'
import { Route as PrivateManageReservesRouteImport } from './routes/_private/manage-reserves'
import { Route as PrivateManageSpacesRouteImport } from './routes/_private/manage-spaces'
import { Route as PrivateManageUsersRouteImport } from './routes/_private/manage-users'
import { Route as PrivateReportRouteImport } from './routes/_private/report'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicForgetPasswordRouteImport } from './routes/_public/forget-password'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateHistoryRoute = PrivateHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateHomeRoute = PrivateHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateManageReservesRoute = PrivateManageReservesRouteImport.update({
  id: '/manage-reserves',
  path: '/manage-reserves',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateManageSpacesRoute = PrivateManageSpacesRouteImport.update({
  id: '/manage-spaces',
  path: '/manage-spaces',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateManageUsersRoute = PrivateManageUsersRouteImport.update({
  id: '/manage-users',
  path: '/manage-users',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateReportRoute = PrivateReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicForgetPasswordRoute = PublicForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/history': typeof PrivateHistoryRoute
  '/home': typeof PrivateHomeRoute
  '/manage-reserves': typeof PrivateManageReservesRoute
  '/manage-spaces': typeof PrivateManageSpacesRoute
  '/manage-users': typeof PrivateManageUsersRoute
  '/report': typeof PrivateReportRoute
  '/forget-password': typeof PublicForgetPasswordRoute
  '/sign-up': typeof PublicSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/history': typeof PrivateHistoryRoute
  '/home': typeof PrivateHomeRoute
  '/manage-reserves': typeof PrivateManageReservesRoute
  '/manage-spaces': typeof PrivateManageSpacesRoute
  '/manage-users': typeof PrivateManageUsersRoute
  '/report': typeof PrivateReportRoute
  '/forget-password': typeof PublicForgetPasswordRoute
  '/sign-up': typeof PublicSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/history': typeof PrivateHistoryRoute
  '/_private/home': typeof PrivateHomeRoute
  '/_private/manage-reserves': typeof PrivateManageReservesRoute
  '/_private/manage-spaces': typeof PrivateManageSpacesRoute
  '/_private/manage-users': typeof PrivateManageUsersRoute
  '/_private/report': typeof PrivateReportRoute
  '/_public/forget-password': typeof PublicForgetPasswordRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/home'
    | '/manage-reserves'
    | '/manage-spaces'
    | '/manage-users'
    | '/report'
    | '/forget-password'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/home'
    | '/manage-reserves'
    | '/manage-spaces'
    | '/manage-users'
    | '/report'
    | '/forget-password'
    | '/sign-up'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/history'
    | '/_private/home'
    | '/_private/manage-reserves'
    | '/_private/manage-spaces'
    | '/_private/manage-users'
    | '/_private/report'
    | '/_public/forget-password'
    | '/_public/sign-up'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/history': {
      id: '/_private/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof PrivateHistoryRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/home': {
      id: '/_private/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PrivateHomeRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/manage-reserves': {
      id: '/_private/manage-reserves'
      path: '/manage-reserves'
      fullPath: '/manage-reserves'
      preLoaderRoute: typeof PrivateManageReservesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/manage-spaces': {
      id: '/_private/manage-spaces'
      path: '/manage-spaces'
      fullPath: '/manage-spaces'
      preLoaderRoute: typeof PrivateManageSpacesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/manage-users': {
      id: '/_private/manage-users'
      path: '/manage-users'
      fullPath: '/manage-users'
      preLoaderRoute: typeof PrivateManageUsersRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/report': {
      id: '/_private/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof PrivateReportRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/forget-password': {
      id: '/_public/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof PublicForgetPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateHistoryRoute: typeof PrivateHistoryRoute
  PrivateHomeRoute: typeof PrivateHomeRoute
  PrivateManageReservesRoute: typeof PrivateManageReservesRoute
  PrivateManageSpacesRoute: typeof PrivateManageSpacesRoute
  PrivateManageUsersRoute: typeof PrivateManageUsersRoute
  PrivateReportRoute: typeof PrivateReportRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateHistoryRoute: PrivateHistoryRoute,
  PrivateHomeRoute: PrivateHomeRoute,
  PrivateManageReservesRoute: PrivateManageReservesRoute,
  PrivateManageSpacesRoute: PrivateManageSpacesRoute,
  PrivateManageUsersRoute: PrivateManageUsersRoute,
  PrivateReportRoute: PrivateReportRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicForgetPasswordRoute: typeof PublicForgetPasswordRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicForgetPasswordRoute: PublicForgetPasswordRoute,
  PublicSignUpRoute: PublicSignUpRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
