/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as PrivateReportarRouteImport } from './pages/_private/reportar'

const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateReportarRoute = PrivateReportarRouteImport.update({
  id: '/_private/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/reportar': typeof PrivateReportarRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/reportar': typeof PrivateReportarRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private/reportar': typeof PrivateReportarRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/reportar' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/reportar' | '/'
  id: '__root__' | '/_private/reportar' | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateReportarRoute: typeof PrivateReportarRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/reportar': {
      id: '/_private/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof PrivateReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PrivateReportarRoute: PrivateReportarRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
